baseURL = "https://njncalub.github.io/"
canonifyurls = true

title = "njncalub $"
copyright = "Copyright &copy; 2018 &mdash; Nap Labs"
languageCode = "en-us"
theme = "kiera"

paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "njncalub-ghpages"
googleAnalytics = "UA-107992935-1"

[author]
    name = "Nap Joseph Calub"
    github = "njncalub"
    gitlab = "njncalub"
    linkedin = "njncalub"
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "Learning something new everyday."

[taxonomies]
  category = "categories"
  tag = "tags"
