baseURL = "https://njncalub.github.io/"
canonifyurls = true

copyright = "Copyright &copy; 2018 &mdash; Nap Labs"
languageCode = "en-us"
theme = "kiera"

paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "njncalub-ghpages"
googleAnalytics = "UA-107992935-1"

title = "fabri de magia"
[params]
    subtitle = "the makers of magic"
    tagline = "a grimoire on software development & design"
    mainSections = [
        "posts",
        "updates"
    ]

[author]
    name = "Nap Joseph Calub"
    github = "njncalub"
    gitlab = ""
    linkedin = "njncalub"
    keybase = "njncalub"
    facebook = ""
    twitter = ""
    instagram = ""
    resume = "https://njncalub.github.io/resume"
    learning = "/continuous-learning"

[taxonomies]
  category = "categories"
  tag = "tags"

[blackfriday]
    fractions = false
